//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Projects = new HashSet<Project>();
            this.Users = new HashSet<User>();
            this.ProjectTasks = new HashSet<ProjectTask>();
            this.ProjectTasks1 = new HashSet<ProjectTask>();
        }
    
        public System.Guid EmployeeID { get; set; }
        public string FullName { get; set; }
        public int RoleID { get; set; }
        public System.DateTime JobStartDate { get; set; }
        public int WorkMethodID { get; set; }
        public string Languages { get; set; }
        public Nullable<decimal> WordPrice { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public bool IsActivated { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
    
        public virtual ValEmployeeRole ValEmployeeRole { get; set; }
        public virtual ValEmployeeWorkMethod ValEmployeeWorkMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTask> ProjectTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTask> ProjectTasks1 { get; set; }
    }
}
