//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid PaymentID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public string Item { get; set; }
        public bool PaymentDirection { get; set; }
        public decimal Paid { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public string Note { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
