//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        public System.Guid TaskID { get; set; }
        public System.Guid ProjectID { get; set; }
        public System.Guid TranslatorID { get; set; }
        public System.Guid ReviewerID { get; set; }
        public int TaskSerial { get; set; }
        public string TaskStatus { get; set; }
        public string TaskFile { get; set; }
        public string TaskDescription { get; set; }
        public long WordCount { get; set; }
        public decimal TranslatorWordPrice { get; set; }
        public System.DateTime TranslatorDeadLine { get; set; }
        public Nullable<System.DateTime> isMailSentToTranslator { get; set; }
        public Nullable<System.DateTime> isTranslatorReceived { get; set; }
        public Nullable<System.DateTime> isTranslatorProgress { get; set; }
        public Nullable<System.DateTime> isTranslatorDone { get; set; }
        public string TranslatorFile { get; set; }
        public string TranslatorNote { get; set; }
        public Nullable<decimal> TranslatorQuality { get; set; }
        public Nullable<int> TranslatorDelay { get; set; }
        public decimal ReviewerWordPrice { get; set; }
        public System.DateTime ReviewerDeadLine { get; set; }
        public Nullable<System.DateTime> isMailSentToReviewer { get; set; }
        public Nullable<System.DateTime> isReviewerReceived { get; set; }
        public Nullable<System.DateTime> isReviewerProgress { get; set; }
        public Nullable<System.DateTime> isReviewerDone { get; set; }
        public string ReviewerFile { get; set; }
        public string ReviewerNote { get; set; }
        public Nullable<decimal> ReviewerQuality { get; set; }
        public Nullable<int> ReviewerDelay { get; set; }
        public bool IsActivated { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Project Project { get; set; }
    }
}
