//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid UserID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActivated { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> AlertProject { get; set; }
        public Nullable<int> AlertTask { get; set; }
        public Nullable<int> AlertPayment { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
