//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValState()
        {
            this.ValCities = new HashSet<ValCity>();
        }
    
        public int StateID { get; set; }
        public string StateText { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValCity> ValCities { get; set; }
        public virtual ValCountry ValCountry { get; set; }
    }
}
